DROP TABLE IF EXISTS customer_shopping_data;

select * from customer_data limit 20

select COUNT(*) FROM customer_data;

-- Q1. Total revenue generated by Male vs. Female customers?
select gender, sum(purchase_amount) as Revenue  
from customer_data 
group by gender;

-- Q2. Customers who used a discount but still spent more than the average purchase amount?

with AveragePrice as(
  select avg(purchase_amount) as avg_amt
  from customer_data
)
select customer_id,discount_applied from  customer_data ,AveragePrice
where discount_applied =  'Yes'
and purchase_amount > AveragePrice.avg_amt;

-- Q3. Top 5 products with the highest average review rating?

with average_review_rating as(
select item_purchased ,avg(review_rating) as avg_rev
from customer_data
group by item_purchased
)
select item_purchased,average_review_rating from customer_data
order by average_review_rating.avg_rev
limit 5

-- Q4. Compare average Purchase Amounts between Standard and Express Shipping.
select shipping_type,round(avg(purchase_amount::numeric),2)
from customer_data
where shipping_type in ('Standard','Express')
group by shipping_type

-- Q5. Do subscribed customers spend more?
select subscription_status,
count(customer_id) as total_customer,
round(avg(purchase_amount::numeric),2) as avg_spend,
round(sum(purchase_amount::numeric),2)as total_revenue
from customer_data
group by subscription_status
order by total_revenue,avg_spend desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end )/count(*),2) as discount_rate
from customer_data
group by item_purchased
order by discount_rate desc;

-- Q7. Segment customers into New, Returning, and Loyal based on total previous purchases.
with customer_type as (select customer_id,
previous_purchases, case
when previous_purchases = 1 then 'new'
when previous_purchases between 2 and 10 then 'Returning'
else 'loyal'
end as customer_segment
from customer_data
)
select customer_segment, count(*) as total_customer
from customer_type
group by customer_segment

-- Q8. What are the top 3 most purchased products within each category?
with most_popular as (
select item_purchased,
category, count(customer_id) as total_customer,
row_number() over(partition by category order by count(customer_id)desc) as item_rank
from customer_data 
group by category,item_purchased
)
select 
item_rank,category,item_purchased,total_customer
from most_popular
where item_rank <= 3 ;

-- Q9. Are repeat buyers (more than 5 previous purchases) likely to subscribe?

select subscription_status,count(customer_id) as repeat_buyers 
from customer_data 
where previous_purchases >= 5 
group by subscription_status;

-- Q10. What is the revenue contribution of each age group?
select age_group,sum(purchase_amount) as revenue_contribution
from customer_data
group by age_group order by revenue_contribution desc;